### PR TITLE
Update Thunderbird product details for 68

### PR DESCRIPTION
**Pull request by darktrojan**
I ran `python manage.py update_product_details`. It did what it's supposed to do, although I don't know how.

Crucially, it's updated `LATEST_THUNDERBIRD_VERSION` and that's all I really wanted.

### CODE REVIEW

**Comment by Sancus** [comment]
This should never involve a code update... it's supposed to update automatically.

**Comment by Sancus** [comment]
Looks like I need to run the cron that updates this on both web servers... should be fixed now because I see add-ons defaulting to their 68 versions when I go to the site in a web browser.

**Comment by darktrojan** [comment]
Are you sure about that?

image

**Comment by Sancus** [comment]
Well, I know that product details is updated and is now returning 68 on both web servers, yes.
```
>>> product_details.thunderbird_versions['LATEST_THUNDERBIRD_VERSION']
u'68.0'
```

**Comment by Sancus** [comment]
OK, I fully restarted BOTH web servers and now that add-on seems to show the 68 version.

Long term we're going to have to rewrite this anyway, since product details gets removed from addons-server in January or so... and then they just rely on the versions in the database instead.

Might just add it to settings.py honestly, so then we have full control over changing it when we want to change it, and only when we want to.

**Pull request closed without merging**
