### PR TITLE
Assume WebExtensions are for Thunderbird

### PR DESCRIPTION
**Pull request by darktrojan**
This should deal with at least the first four parts of #50.

### CODE REVIEW

**Comment by Sancus** [comment]
Did you test add-on upload with this patch? As far as I can tell, it breaks uploads. The platforms area is greyed out, but the site won't accept the upload without a platform specified.

**Comment by darktrojan** [comment]
Oh hang on, I've looked at the wrong patch, will try again.

**Comment by Sancus** [comment]
I'm not sure what type of add-on you've been testing with. I tried uploading a new version of Reminderfox(the stage database was a bit old so it only had 2.6.6.3) and the upload process insists on having a platform set or it will error "Need at least one platform."

**Comment by Sancus** [comment]
OK, this works. Hopefully there's nothing we missed that will turn up additional errors or issues.

**Pull request merged**
