### PR TITLE
update github issues links from mozilla/addons-server to thundernest

### LINKED ISSUE #29: Update support details to point to support relevant to addons.thunderbird.net
Clicking the "Report a bug" link on https://addons.thunderbird.net/ points to the support page information for add-ons which is more relevant to Firefox clients. This linkshould be changed to provide support info relevant for Thunderbird.

themes____add-ons_for_thunderbird

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #29

### CODE REVIEW

**Comment by muffinresearch** [comment]
@Sancus Any ETA on when this will be deployed? We're still getting bug reports.

**Comment by Sancus** [comment]
It's deployed now. I suspect [this is the link](https://addons.thunderbird.net/en-US/thunderbird/addon/10900/) where these reports are coming from. Because you can't download lightweight themes via browser, we need to change the "Add' link for LWT to point at a support article explaining how to install them from within Thunderbird.

**Comment by muffinresearch** [comment]
The "report a bug" link in the footer still points to `https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact` and we're still getting reports.

**Comment by muffinresearch** [comment]
This didn't actually fix #29 - I've moved the details to the issue.

**Pull request merged**
