### PR TITLE
Add-on templates Updated for ATN

### PR DESCRIPTION
**Pull request by ryanleesipes**
Adjusted Add-on Email templates to reflect being a part of ATN, and point at ATN-related resources.

### CODE REVIEW

**Comment by ryanleesipes** [comment]
@Sancus or @kewisch who should review this kind of stuff?

**Comment by ryanleesipes** [comment]
@Sancus can this be merged now?

**Comment by ryanleesipes** [comment]
@Sancus I see we've merged master into addon templates. What's the next step here? Does it look like they changed a bunch?

**Comment by Sancus** [comment]
These template changes are live.

**Pull request merged**
