### PR TITLE
Stop considering some extensions for auto-approval

### PR DESCRIPTION
**Pull request by darktrojan**
Based on what @Sancus just told me, this isn't going to work and will leave some extensions in No Man's Land, but here it is.

### CODE REVIEW

**Comment by kewisch** [comment]
What add-ons are some add-ons? Are there tests for this that need to be adapted or written?

**Comment by darktrojan** [comment]
We're talking about extensions the use the new overlay loader, which are technically WebExtensions and therefore get auto-approval. Also WebExtension experiments.

Note that we don't actually intend to land this particular change.

**Comment by darktrojan** [comment]
With the change I just pushed and the one earlier today, this code now actually works, and the un-auto-approved extensions appear in the review queues.

Over to you, @Sancus.

**Comment by Sancus** [comment]
@darktrojan I think we should separate the experiments part out, and leave them auto approved for now. You still have to be part of the group, and really the only one doing experimentation right now is BenB, and I'm not sure pushing his frequent iteration into the regular approval queue makes sense.

So maybe just do this for is restart required addons.

**Comment by darktrojan** [comment]
I've commented out the appropriate lines, we might want to do something cleverer if we change our mind on the matter, but it's there if we just want to flick the switch. (I haven't tested this latest change at all.)

**Comment by Sancus** [comment]
I tested this and it works, although it's a pretty buggy alteration because as far as the site is concerned, it's still a Web Extension and therefore subject to auto approval. Which means that it still gets a comment/UI in the reviewer tools saying that it's waiting for auto approval, and a button to enable/disable auto approval, and a flag saying it's a web extension.

And probably lots of other things. I'm not sure it's really possible to root all of those out without changing the upload process to *not* flag these add-ons as web extensions at all in the first place, but I have no idea if that will cause other unintended consequences.

legacy: true was a mistake.

**Comment by darktrojan** [comment]
They *are* web extensions. Just with a stupidly-permissive API.

If you can send some screenshots of stuff you'd like changed, or even just the exact wording of strings, I'll see if we can do that.

**Comment by Sancus** [comment]
> If you can send some screenshots of stuff you'd like changed, or even just the exact wording of strings, I'll see if we can do that.

I don't really think it's a good use of your time. As far as I can tell it's mostly cosmetic stuff in the reviewer/admin UI. If I see anything seriously bugging that breaks functionality I'll file it.

**Pull request merged**
